version: "3.9"

services:
    nginx:
        container_name: "app-nginx"
        restart: unless-stopped
        build:
            context: ./dockerfile/nginx
            dockerfile: nginx.dockerfile
        ports:
            - 80:80
        environment:
            - NGINX_HOST=local.work.com
            - NGINX_PORT=80
        links:
            - php
        volumes:
            - ./www:/var/www/app
            - ./logs:/var/log/nginx
    php:
        container_name: "app-php"
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./dockerfile/php/php.dockerfile
        volumes:
          - ./www:/var/www/app
          - /var/www/app/node_modules
          - /var/www/app/vendor
        links:
            - db
    db:
      image: mysql:8.1
      restart: unless-stopped
      ports:
        - 3306:3306
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=local.work.ru
      volumes:
        - ./mysql-data:/var/lib/mysql
        - /etc/localtime:/etc/localtime
